fix: TR-1197 proceed firefox/chrome fullscreen via F11 key
oat-sa/extension-tao-test-runner-plugins pull request #189
Opened 2021-05-12 10:51 UTC by lecosson

Related to: https://oat-sa.atlassian.net/browse/TR-1197

- fullscreen warning popup no more shows after switch to fullscreen mode via F11 (webkit/mozilla)

Requires: none

2021-05-17 11:54 UTC, marpesia commented
The code looks fine and works in most cases :) 

I've tried on Chrome with weird behaviour, It looks like it is not being triggered on every screen resolution, but it could be just me (I have several monitors with different resolutions... :S)

In Firefox (88.0.1 linux), if I click several times F11, I get this error when it is fullscreen. Can you check if it happens to you?
![image](https://user-images.githubusercontent.com/11692751/118483223-0e2e2200-b716-11eb-83ce-72238592ef85.png)

2021-05-18 09:41 UTC, jsconan requested changes
Well, it works, but the implementation is not correct.
Please see my comments below.

Here is a summary:
- the `resize` event needs to be throttled
- the alert dialog offers an api to close it, no need to pass through an unsafe trick to tamper with the css selector
- naming does not look accurate and may be confusing
- an existing handler already takes care of the check, better to enhance it with the dialog autoclosure

2021-05-18 09:41 UTC, jsconan commented on views/js/runner/plugins/security/fullScreen.js
> +            const mozWebkitFullScreen = screen.width === window.outerWidth && screen.height === window.outerHeight;
**nitpick:** I wonder if the name is accurate. Is it actually related to Mozilla or Webkit? I'd rather name it `screenSizeCheck` or `isSizeFullscreen`...

2021-05-18 09:41 UTC, jsconan commented on views/js/runner/plugins/security/fullScreen.js
> +            function handleResizeToFullScreenChange() {
**question:** Why is it needed to add this function? We already have the `handleFullScreenChange()`, [line 318](https://github.com/oat-sa/extension-tao-test-runner-plugins/blob/21c6b6d5c82eb2ccd694c2c58e3ca0390e8e9276/views/js/runner/plugins/security/fullScreen.js#L318). The only missing part is the dialog closure when the fullscreen is set: `testRunner.trigger('closedialog.fullscreen');`

**suggestion:** Enhance the existing handler
```javascript
            function handleFullScreenChange() {
                isFullScreen = checkFullScreen();
                if (!isFullScreen) {
                    leaveFullScreen(testRunner);
                    alertUser();
                } else {
                    enterFullScreen(testRunner);
                    testRunner.trigger('closedialog.fullscreen');
                }
            }
```

2021-05-18 17:31 UTC, lecosson commented
> The code looks fine and works in most cases :)
> 
> I've tried on Chrome with weird behaviour, It looks like it is not being triggered on every screen resolution, but it could be just me (I have several monitors with different resolutions... :S)
> 
> In Firefox (88.0.1 linux), if I click several times F11, I get this error when it is fullscreen. Can you check if it happens to you?
> ![image](https://user-images.githubusercontent.com/11692751/118483223-0e2e2200-b716-11eb-83ce-72238592ef85.png)

Request for fullscreen was denied because Element.requestFullscreen() was not called from inside a short running user-generated event handler. catched for logging

2021-05-19 08:46 UTC, marpesia approved these changes
Nice job!

There are several commits with the same comment. 
Maybe you could be more specific to set the purpose of that specific commit.

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-05-19 09:32 UTC, btamas requested changes

2021-05-19 09:32 UTC, btamas commented on views/js/runner/plugins/security/fullScreen.js
> +    /* 'core/logger', // uncomment to enable fullscreen request denied logging */
Would you like to keep these lines, I think you should remove them.

2021-05-19 12:56 UTC, btamas reviewed
It does not work correctly on my macbook. Do I do something wrong?
If I press Ctrl + Command + F, it goes to fullscreen, but the modal is there. If I press it again, browser jumps out from fullscreen, the dialog disappears and jumps back to fullscreen immediately. If I press it again, it goes out from fullscreen and I have the dialog again. And this cycle continues.

https://user-images.githubusercontent.com/537151/118816003-0efbbb00-b8b2-11eb-9aac-2cefce77f060.mov

2021-05-19 14:41 UTC, lecosson commented
> It does not work correctly on my macbook. Do I do something wrong?

No, you are right. issue appears on mac platform after add throttling, resolved by using _.delay instead of _.defer (that internally implemented as `_.delay(f(){...},1)`). Thank you, nice catch!

2021-05-20 10:36 UTC, btamas approved these changes
Works correctly for me now.
The only request is please use better commit messages next time. Almost all of them are the same and they are common, so based on the message, I would not be able to figure out what did you modified in the code.

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-05-20 10:46 UTC, lecosson commented
> Works correctly for me now.
> The only request is please use better commit messages next time. Almost all of them are the same and they are common, so based on the message, I would not be able to figure out what did you modified in the code.

More detailed messages for commits can be viewed by expand it with little buttons on right side of commits messages
![image](https://user-images.githubusercontent.com/8062729/118965857-cacfef80-b971-11eb-8ffb-bd2494e0536b.png)

2021-05-20 10:49 UTC, merged